"""
Step 2 — PDF Parsing Pipeline
Extracts structured data from EPD PDF datasheets using pdfplumber.
Handles the sample PDFs generated by generate_sample_epd.py as well as
real EPD PDFs from the 2050-materials API.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path

import pdfplumber


@dataclass
class EPDRecord:
    """Structured output of a parsed EPD PDF."""
    product_name: str = ""
    company: str = ""
    location: str = ""
    country: str = ""
    declared_unit: str = ""
    gwp_per_declared_unit: float | None = None  # kg CO2e per declared unit (A1-A3)
    gwp_per_kg: float | None = None             # kg CO2e per kg
    density_kg_m3: float | None = None
    epd_number: str = ""
    valid_until: str = ""
    material_category: str = ""
    raw_text: str = field(default="", repr=False)


# ── Regex patterns ────────────────────────────────────────────────────────────

_GWP_PATTERNS = [
    # "Global Warming Potential (GWP)   280.5   kg CO2e / 1 m³"
    # Flexible: CO₂e may extract as CO2e, COne, COe, CO2e etc. due to font encoding
    re.compile(
        r"Global\s+Warming\s+Potential[^\n]*?(\d[\d\s,\.]+)\s*kg",
        re.IGNORECASE | re.DOTALL,
    ),
    # Table row: "GWP   1820.0   kg ..."  (not the "per kg" row)
    re.compile(
        r"^GWP\b(?!\s+per\s+kg)[^\n]*?(\d[\d\s,\.]+)\s*kg",
        re.IGNORECASE | re.MULTILINE,
    ),
]

_GWP_PER_KG_PATTERNS = [
    # "GWP per kg   0.0291   kg ..."
    re.compile(
        r"GWP\s+per\s+kg[^\n]*?(\d[\d,\.]+)\s*kg",
        re.IGNORECASE,
    ),
    # fallback: any "0.0xxx kg ... / kg" pattern
    re.compile(
        r"(0\.\d{3,6})\s*kg[^\n]*/\s*kg",
        re.IGNORECASE,
    ),
]

_EPD_NUMBER_PATTERN = re.compile(r"EPD[-\s]?(?:Number|No\.?|#)?\s*[:\-]?\s*(EPD[-\w]+)", re.IGNORECASE)
_VALID_UNTIL_PATTERN = re.compile(r"Valid\s+(?:Until|Until:|to)\s*[:\-]?\s*(\d{4}[-/]\d{2}[-/]\d{2})", re.IGNORECASE)
_DENSITY_PATTERN = re.compile(r"Density\s*[:\|]?\s*(\d[\d,\.]+)\s*kg/m[³3]", re.IGNORECASE)
_DECLARED_UNIT_PATTERN = re.compile(r"Declared\s+Unit\s*[:\|]?\s*(.+?)(?:\n|$)", re.IGNORECASE)
_MANUFACTURER_PATTERN = re.compile(r"(?:Manufacturer|Company)\s*[:\|]?\s*(.+?)(?:\n|$)", re.IGNORECASE)
_LOCATION_PATTERN = re.compile(r"(?:Location\s+of\s+Production|Location)\s*[:\|]?\s*(.+?)(?:\n|$)", re.IGNORECASE)
_COUNTRY_PATTERN = re.compile(r"Country\s*[:\|]?\s*([A-Z]{2,3})\b", re.IGNORECASE)
_CATEGORY_PATTERN = re.compile(r"Material\s+Category\s*[:\|]?\s*(.+?)(?:\n|$)", re.IGNORECASE)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _clean_number(s: str) -> float | None:
    """Convert a raw matched string like '1 820.0' or '280,5' to float."""
    cleaned = s.strip().replace(" ", "").replace(",", ".")
    try:
        return float(cleaned)
    except ValueError:
        return None


def _first_match(pattern: re.Pattern, text: str, group: int = 1) -> str:
    m = pattern.search(text)
    return m.group(group).strip() if m else ""


def _first_number(patterns: list[re.Pattern], text: str) -> float | None:
    for pattern in patterns:
        m = pattern.search(text)
        if m:
            return _clean_number(m.group(1))
    return None


# ── Core parser ───────────────────────────────────────────────────────────────

def parse_epd_pdf(pdf_path: str | Path) -> EPDRecord:
    """
    Parse a single EPD PDF and return a structured EPDRecord.

    Extraction strategy:
    1. Dump all text from all pages via pdfplumber
    2. Apply regex patterns to find each field
    3. For product name, use the first non-empty line of page 1
    """
    pdf_path = Path(pdf_path)
    record = EPDRecord()

    with pdfplumber.open(pdf_path) as pdf:
        pages_text = [page.extract_text() or "" for page in pdf.pages]

    full_text = "\n".join(pages_text)
    record.raw_text = full_text

    # Product name — first meaningful line on page 1 (skip the header banner)
    for line in pages_text[0].splitlines():
        stripped = line.strip()
        if stripped and "ENVIRONMENTAL PRODUCT DECLARATION" not in stripped.upper():
            record.product_name = stripped
            break

    record.company = _first_match(_MANUFACTURER_PATTERN, full_text)
    record.location = _first_match(_LOCATION_PATTERN, full_text)
    record.country = _first_match(_COUNTRY_PATTERN, full_text).upper()
    record.declared_unit = _first_match(_DECLARED_UNIT_PATTERN, full_text)
    record.epd_number = _first_match(_EPD_NUMBER_PATTERN, full_text)
    record.valid_until = _first_match(_VALID_UNTIL_PATTERN, full_text)
    record.material_category = _first_match(_CATEGORY_PATTERN, full_text)
    record.density_kg_m3 = _first_number([_DENSITY_PATTERN], full_text)

    # GWP — try per-declared-unit first (the highlighted row), then per-kg
    record.gwp_per_declared_unit = _first_number(_GWP_PATTERNS, full_text)
    record.gwp_per_kg = _first_number(_GWP_PER_KG_PATTERNS, full_text)

    return record


def parse_all_pdfs(pdf_dir: str | Path) -> list[EPDRecord]:
    """Parse every PDF in a directory and return a list of EPDRecords."""
    pdf_dir = Path(pdf_dir)
    records = []
    for pdf_file in sorted(pdf_dir.glob("*.pdf")):
        record = parse_epd_pdf(pdf_file)
        records.append(record)
    return records
