import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useBuilding } from "@/state/building";
import { CATEGORY_LABELS, getMaterial } from "./materials";
import { elementCO2kg, suggestSwaps, totalCO2kg } from "./carbon";
import { captureViewport } from "@/components/carbon/Viewport";

// Brand
const PINE: [number, number, number] = [44, 95, 76];
const PINE_MID: [number, number, number] = [74, 128, 112];
const PINE_LITE: [number, number, number] = [107, 157, 131];
const INK: [number, number, number] = [20, 20, 20];
const BODY: [number, number, number] = [51, 51, 51];
const MUTED: [number, number, number] = [110, 110, 110];
const RULE: [number, number, number] = [224, 224, 224];
const ROW_ALT: [number, number, number] = [248, 248, 248];

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;

const BENCHMARK_KG_PER_M2 = 240; // industry avg
const PROJECT = "Barcelona Poble Nou Tower";
const LOCATION = "Barcelona, Poble Nou";

const setText = (doc: jsPDF, size: number, color: [number, number, number], style: "normal" | "bold" | "italic" = "normal") => {
  doc.setFontSize(size);
  doc.setTextColor(color[0], color[1], color[2]);
  doc.setFont("helvetica", style);
};

const drawHeader = (doc: jsPDF, pageNum: number) => {
  setText(doc, 8, MUTED);
  doc.text("EMBODIED CARBON TOOL  /  Barcelona Poble Nou", MARGIN, 12);
  doc.setDrawColor(...PINE);
  doc.setLineWidth(0.6);
  doc.line(MARGIN, 14, PAGE_W - MARGIN, 14);
  setText(doc, 8, MUTED);
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN, 12, { align: "right" });
};

const drawFooter = (doc: jsPDF) => {
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, PAGE_H - 14, PAGE_W - MARGIN, PAGE_H - 14);
  setText(doc, 7, MUTED, "italic");
  doc.text(
    "Generated by Embodied Carbon Assessment Tool  •  Data: materialepyramiden.dk (KADK/CINARK)",
    PAGE_W / 2,
    PAGE_H - 9,
    { align: "center" },
  );
};

const sectionTitle = (doc: jsPDF, y: number, label: string) => {
  setText(doc, 16, INK, "bold");
  doc.text(label, MARGIN, y);
  doc.setDrawColor(...PINE);
  doc.setLineWidth(0.8);
  doc.line(MARGIN, y + 2, MARGIN + 14, y + 2);
};

const eyebrow = (doc: jsPDF, y: number, label: string) => {
  setText(doc, 8, PINE, "bold");
  doc.text(label.toUpperCase(), MARGIN, y);
};

export const downloadPassport = async () => {
  const { elements, dims } = useBuilding.getState();
  const totalKg = totalCO2kg(elements);
  const totalT = totalKg / 1000;
  const floors = Math.max(1, Math.round(dims.height / 3));
  const grossArea = dims.width * dims.depth * floors;
  const kgPerM2 = totalKg / Math.max(1, grossArea);
  const benchDelta = ((kgPerM2 - BENCHMARK_KG_PER_M2) / BENCHMARK_KG_PER_M2) * 100;
  const today = new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" });

  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ============ COVER ============
  // Hairline frame
  doc.setDrawColor(...PINE);
  doc.setLineWidth(0.4);
  doc.rect(MARGIN - 4, MARGIN - 4, PAGE_W - 2 * (MARGIN - 4), PAGE_H - 2 * (MARGIN - 4));

  setText(doc, 8, PINE, "bold");
  doc.text("EMBODIED CARBON TOOL", MARGIN, 30);
  doc.setDrawColor(...PINE);
  doc.line(MARGIN, 32, MARGIN + 30, 32);

  setText(doc, 28, INK, "bold");
  doc.text("MATERIAL", MARGIN, 52);
  doc.text("PASSPORT", MARGIN, 64);
  setText(doc, 11, MUTED);
  doc.text("Embodied Carbon Assessment  •  EN 15978  •  A1–A3", MARGIN, 72);

  // Building snapshot
  const img = captureViewport();
  const imgY = 82;
  const imgH = 95;
  if (img) {
    try {
      doc.addImage(img, "PNG", MARGIN, imgY, PAGE_W - 2 * MARGIN, imgH);
      doc.setDrawColor(...RULE);
      doc.setLineWidth(0.3);
      doc.rect(MARGIN, imgY, PAGE_W - 2 * MARGIN, imgH);
    } catch {
      /* ignore */
    }
  }

  // Project info grid
  let infoY = imgY + imgH + 12;
  const colW = (PAGE_W - 2 * MARGIN) / 4;
  const infoCells: [string, string][] = [
    ["Project", PROJECT],
    ["Location", LOCATION],
    ["Date", today],
    ["Gross area", `${grossArea.toLocaleString()} m²`],
  ];
  infoCells.forEach(([k, v], i) => {
    setText(doc, 7, MUTED, "bold");
    doc.text(k.toUpperCase(), MARGIN + i * colW, infoY);
    setText(doc, 11, INK, "bold");
    doc.text(v, MARGIN + i * colW, infoY + 6);
  });

  // Hero metric
  const heroY = infoY + 22;
  doc.setFillColor(...PINE);
  doc.rect(MARGIN, heroY, PAGE_W - 2 * MARGIN, 38, "F");
  setText(doc, 8, [255, 255, 255], "bold");
  doc.text("TOTAL EMBODIED CARBON", MARGIN + 6, heroY + 9);
  setText(doc, 32, [255, 255, 255], "bold");
  doc.text(`${totalT.toFixed(1)}`, MARGIN + 6, heroY + 28);
  setText(doc, 12, [255, 255, 255]);
  doc.text("t CO2e", MARGIN + 6 + doc.getTextWidth(totalT.toFixed(1)) + 4, heroY + 28);
  setText(doc, 9, [255, 255, 255]);
  doc.text(`${kgPerM2.toFixed(0)} kg CO2e / m²`, PAGE_W - MARGIN - 6, heroY + 28, { align: "right" });

  setText(doc, 7, MUTED, "italic");
  doc.text("Generated by Embodied Carbon Assessment Tool", PAGE_W / 2, PAGE_H - 14, { align: "center" });

  // ============ PAGE 2 — EXECUTIVE SUMMARY ============
  doc.addPage();
  drawHeader(doc, 2);
  let y = 28;
  sectionTitle(doc, y, "Executive Summary");
  y += 10;

  setText(doc, 10, BODY);
  const overview =
    "This material passport documents the embodied carbon associated with the construction of the building described above. " +
    "Quantities are estimated from the project's massing model; emissions factors are sourced from MaterialePyramiden EPD data " +
    "covering life-cycle phases A1–A3 (cradle-to-gate), in accordance with EN 15978.";
  doc.text(doc.splitTextToSize(overview, PAGE_W - 2 * MARGIN), MARGIN, y);
  y += 22;

  // Key metric cards
  const cardW = (PAGE_W - 2 * MARGIN - 8) / 3;
  const cardH = 28;
  const cards: [string, string, string][] = [
    ["Total CO2", `${totalT.toFixed(1)} t`, "CO2e (A1–A3)"],
    ["Intensity", `${kgPerM2.toFixed(0)}`, "kg CO2e / m²"],
    [
      "vs Benchmark",
      `${benchDelta >= 0 ? "+" : ""}${benchDelta.toFixed(0)}%`,
      `Industry avg ${BENCHMARK_KG_PER_M2} kg/m²`,
    ],
  ];
  cards.forEach(([label, num, sub], i) => {
    const x = MARGIN + i * (cardW + 4);
    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.3);
    doc.rect(x, y, cardW, cardH);
    doc.setFillColor(...PINE);
    doc.rect(x, y, 1.2, cardH, "F");
    setText(doc, 7, MUTED, "bold");
    doc.text(label.toUpperCase(), x + 5, y + 6);
    setText(doc, 18, PINE, "bold");
    doc.text(num, x + 5, y + 17);
    setText(doc, 8, MUTED);
    doc.text(sub, x + 5, y + 24);
  });
  y += cardH + 14;

  // Carbon distribution bars
  eyebrow(doc, y, "Carbon Distribution by Element");
  y += 6;
  const barAreaW = PAGE_W - 2 * MARGIN;
  const labelW = 38;
  const valueW = 36;
  const barTrackW = barAreaW - labelW - valueW;
  const maxKg = Math.max(...elements.map((e) => Math.abs(elementCO2kg(e))), 1);
  const palette: [number, number, number][] = [PINE, PINE_MID, PINE_LITE, PINE_MID, PINE];

  elements.forEach((e, i) => {
    const kg = elementCO2kg(e);
    const pct = (Math.abs(kg) / Math.max(1, totalKg || maxKg)) * 100;
    const w = Math.max(1, (Math.abs(kg) / maxKg) * barTrackW);
    setText(doc, 9, INK, "bold");
    doc.text(e.label, MARGIN, y + 4);
    // track
    doc.setFillColor(245, 245, 245);
    doc.rect(MARGIN + labelW, y, barTrackW, 6, "F");
    // bar
    const c = palette[i % palette.length];
    doc.setFillColor(c[0], c[1], c[2]);
    doc.rect(MARGIN + labelW, y, w, 6, "F");
    setText(doc, 9, INK);
    doc.text(`${(kg / 1000).toFixed(1)} t  (${pct.toFixed(0)}%)`, PAGE_W - MARGIN, y + 4, { align: "right" });
    y += 10;
  });

  drawFooter(doc);

  // ============ PAGE 3 — MATERIAL BREAKDOWN ============
  doc.addPage();
  drawHeader(doc, 3);
  y = 28;
  sectionTitle(doc, y, "Material Breakdown");
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [["Element", "Material", "Category", "Volume (m³)", "kg CO2/m³", "Total t CO2"]],
    body: elements.map((e) => {
      const m = getMaterial(e.materialId);
      return [
        e.label,
        m.name,
        CATEGORY_LABELS[m.category].split(" ")[0],
        e.volumeM3.toFixed(0),
        m.co2PerM3.toString(),
        (elementCO2kg(e) / 1000).toFixed(2),
      ];
    }),
    foot: [["", "", "", "", "Total", `${totalT.toFixed(2)} t`]],
    theme: "grid",
    margin: { left: MARGIN, right: MARGIN },
    styles: { font: "helvetica", fontSize: 9, cellPadding: 3, lineColor: RULE, textColor: BODY },
    headStyles: { fillColor: PINE, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
    footStyles: { fillColor: [240, 240, 240], textColor: INK, fontStyle: "bold" },
    alternateRowStyles: { fillColor: ROW_ALT },
    columnStyles: {
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right", fontStyle: "bold", textColor: PINE },
    },
  });

  drawFooter(doc);

  // ============ PAGE 4 — MATERIAL CARDS ============
  doc.addPage();
  drawHeader(doc, 4);
  y = 28;
  sectionTitle(doc, y, "Material Specifications");
  y += 10;

  // Unique materials in use
  const seen = new Set<string>();
  const usedMaterials = elements
    .map((e) => ({ el: e, m: getMaterial(e.materialId) }))
    .filter(({ m }) => (seen.has(m.id) ? false : (seen.add(m.id), true)));

  // Aggregate volume per material
  const volByMat = new Map<string, number>();
  const co2ByMat = new Map<string, number>();
  for (const e of elements) {
    volByMat.set(e.materialId, (volByMat.get(e.materialId) ?? 0) + e.volumeM3);
    co2ByMat.set(e.materialId, (co2ByMat.get(e.materialId) ?? 0) + elementCO2kg(e));
  }

  const cardWidth = (PAGE_W - 2 * MARGIN - 6) / 2;
  const cardHeight = 50;
  let col = 0;
  for (const { m } of usedMaterials) {
    if (y + cardHeight > PAGE_H - 22) {
      drawFooter(doc);
      doc.addPage();
      drawHeader(doc, doc.getNumberOfPages());
      y = 28;
      sectionTitle(doc, y, "Material Specifications (cont.)");
      y += 10;
      col = 0;
    }
    const x = MARGIN + col * (cardWidth + 6);
    // border
    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.3);
    doc.rect(x, y, cardWidth, cardHeight);
    // category swatch strip
    doc.setFillColor(...PINE);
    doc.rect(x, y, cardWidth, 1.2, "F");
    // name
    setText(doc, 11, INK, "bold");
    doc.text(m.name, x + 4, y + 9);
    setText(doc, 7, PINE, "bold");
    doc.text(CATEGORY_LABELS[m.category].split(" ")[0].toUpperCase(), x + 4, y + 14);

    const totalImpact = (co2ByMat.get(m.id) ?? 0) / 1000;
    const sink = m.co2PerM3 < 0;
    const rows: [string, string][] = [
      ["Embodied carbon", `${m.co2PerM3} kg CO2/m³${sink ? "  ◇ sink" : ""}`],
      ["Quantity in project", `${(volByMat.get(m.id) ?? 0).toFixed(0)} m³`],
      ["Total impact", `${totalImpact.toFixed(2)} t CO2e`],
      ["EPD source", "MaterialePyramiden.dk"],
      ["Life cycle", "A1–A3 (cradle-to-gate)"],
    ];
    let ry = y + 20;
    rows.forEach(([k, v]) => {
      setText(doc, 7, MUTED);
      doc.text(k, x + 4, ry);
      setText(doc, 8, INK, "bold");
      doc.text(v, x + cardWidth - 4, ry, { align: "right" });
      ry += 5.5;
    });

    col++;
    if (col === 2) {
      col = 0;
      y += cardHeight + 6;
    }
  }
  drawFooter(doc);

  // ============ PAGE 5 — OPTIMIZATION ============
  doc.addPage();
  drawHeader(doc, doc.getNumberOfPages());
  y = 28;
  sectionTitle(doc, y, "Optimization Opportunities");
  y += 10;
  setText(doc, 10, BODY);
  doc.text(
    doc.splitTextToSize(
      "Same-category material substitutions ranked by potential CO2 savings. Replacing high-impact materials with biobased or reused alternatives is the most direct lever to reduce embodied carbon.",
      PAGE_W - 2 * MARGIN,
    ),
    MARGIN,
    y,
  );
  y += 16;

  const swaps = suggestSwaps(elements);
  if (swaps.length === 0) {
    setText(doc, 10, MUTED, "italic");
    doc.text("All elements already use the lowest-carbon option in their category.", MARGIN, y);
  } else {
    swaps.forEach((s, i) => {
      const blockH = 30;
      doc.setDrawColor(...RULE);
      doc.setLineWidth(0.3);
      doc.rect(MARGIN, y, PAGE_W - 2 * MARGIN, blockH);
      doc.setFillColor(...PINE);
      doc.rect(MARGIN, y, 1.5, blockH, "F");

      setText(doc, 10, PINE, "bold");
      doc.text(`${i + 1}.`, MARGIN + 6, y + 8);
      setText(doc, 11, INK, "bold");
      doc.text(`${s.elementLabel}: ${s.fromMaterial.name} → ${s.toMaterial.name}`, MARGIN + 12, y + 8);

      const curT = (s.fromMaterial.co2PerM3 *
        (elements.find((e) => e.id === s.elementId)?.volumeM3 ?? 0)) /
        1000;
      const newT = (s.toMaterial.co2PerM3 *
        (elements.find((e) => e.id === s.elementId)?.volumeM3 ?? 0)) /
        1000;
      const savingsT = s.savingsKg / 1000;
      const pct = (s.savingsKg / Math.max(1, Math.abs(s.fromMaterial.co2PerM3) *
        (elements.find((e) => e.id === s.elementId)?.volumeM3 ?? 1))) * 100;

      setText(doc, 9, BODY);
      doc.text(`Current:  ${curT.toFixed(1)} t CO2`, MARGIN + 12, y + 16);
      doc.text(`Proposed: ${newT.toFixed(1)} t CO2`, MARGIN + 12, y + 22);

      setText(doc, 8, MUTED, "bold");
      doc.text("SAVINGS", PAGE_W - MARGIN - 6, y + 10, { align: "right" });
      setText(doc, 16, PINE, "bold");
      doc.text(`-${savingsT.toFixed(1)} t`, PAGE_W - MARGIN - 6, y + 19, { align: "right" });
      setText(doc, 9, PINE);
      doc.text(`(-${pct.toFixed(0)}%)`, PAGE_W - MARGIN - 6, y + 25, { align: "right" });

      y += blockH + 6;
    });
  }

  drawFooter(doc);

  // ============ PAGE 6 — METHODOLOGY ============
  doc.addPage();
  drawHeader(doc, doc.getNumberOfPages());
  y = 28;
  sectionTitle(doc, y, "Methodology & References");
  y += 12;

  const sect = (title: string, lines: string[]) => {
    eyebrow(doc, y, title);
    y += 6;
    setText(doc, 10, BODY);
    lines.forEach((l) => {
      doc.text(`•  ${l}`, MARGIN + 2, y);
      y += 5.5;
    });
    y += 6;
  };

  sect("Methodology", [
    "Life Cycle Assessment (LCA) per EN 15978",
    "Phases A1–A3: Product stage (cradle-to-gate)",
    "Quantities estimated from project massing model",
    "Emissions factors from MaterialePyramiden EPD database",
  ]);

  sect("Benchmarks", [
    `Industry average: ${BENCHMARK_KG_PER_M2} kg CO2/m²`,
    `This project: ${kgPerM2.toFixed(0)} kg CO2/m² (${benchDelta >= 0 ? "+" : ""}${benchDelta.toFixed(0)}% vs. average)`,
    "Barcelona Climate Neutrality 2030: 45% reduction target",
  ]);

  sect("References", [
    `Generated: ${today}`,
    "Tool: Embodied Carbon Assessment Tool v1.0",
    "Data: MaterialePyramiden.dk (KADK / CINARK)",
    "Location: 41.4036° N, 2.1900° E",
  ]);

  setText(doc, 8, MUTED, "italic");
  const disclaimer =
    "This passport is indicative. Final embodied-carbon figures should be verified using project-specific EPDs " +
    "and a full bill of quantities. Modules A4–C4 (transport, construction, use, end-of-life) are not included in this assessment.";
  doc.text(doc.splitTextToSize(disclaimer, PAGE_W - 2 * MARGIN), MARGIN, PAGE_H - 30);

  drawFooter(doc);

  doc.save(`material-passport-${new Date().toISOString().slice(0, 10)}.pdf`);
};
