"""
Surround Stage 3 — Material Carbon Analysis Pipeline
Entry point that wires all 7 steps together into a single run.

Usage:
    python run_pipeline.py

Configure inputs in the INPUT CONFIGURATION section below, or pass a .env file
with EPD_API_TOKEN set.

When no API token is set, the pipeline runs in OFFLINE MODE using the sample
EPD PDFs in sample_data/epd_pdfs/ (generated by sample_data/generate_sample_epd.py).
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from pipeline.carbon_calc import SurfaceInput, calculate_all
from pipeline.comparative_table import build_comparative_table, export_table, summary_stats
from pipeline.pdf_parser import parse_all_pdfs, parse_epd_pdf
from pipeline.ranking import rank_materials
from pipeline.report import generate_report

load_dotenv()

# ── INPUT CONFIGURATION ───────────────────────────────────────────────────────

PROJECT_NAME = "22@ Poblenou Residential Block"
SITE_LOCATION = "22@ Poblenou, Barcelona, Spain"
BUILDING_TYPE = "Residential"

# Surfaces from Stage 2 — replace with real values from the massing model
SURFACES: list[SurfaceInput] = [
    SurfaceInput(
        surface_id="roof_01",
        surface_type="roof",
        area_m2=120.0,
        volume_m3=18.0,         # 120 m² × 0.15 m thick
        material_category="wood",
    ),
    SurfaceInput(
        surface_id="wall_north",
        surface_type="wall",
        area_m2=85.0,
        volume_m3=17.0,         # 85 m² × 0.20 m thick
        material_category="concrete",
    ),
    SurfaceInput(
        surface_id="floor_01",
        surface_type="floor",
        area_m2=120.0,
        volume_m3=30.0,         # 120 m² × 0.25 m thick
        material_category="steel",
    ),
]

# PDF source — switch between offline (sample) and downloaded EPDs
SAMPLE_PDF_DIR = Path("sample_data/epd_pdfs")
DOWNLOADS_DIR = Path("downloads/epd_pdfs")
OUTPUT_DIR = Path("output")


# ── PIPELINE ──────────────────────────────────────────────────────────────────

def run():
    OUTPUT_DIR.mkdir(exist_ok=True)
    api_token = os.getenv("EPD_API_TOKEN")
    offline_mode = not api_token

    if offline_mode:
        print("EPD_API_TOKEN not set — running in OFFLINE MODE with sample PDFs.\n")

    surface_rankings = {}

    for surface in SURFACES:
        print(f"-- Surface: {surface.surface_id} ({surface.surface_type}, {surface.area_m2} m2)")

        # Step 1 + 2: get EPD records
        if offline_mode:
            # Use sample PDFs that match the material category
            records = _load_sample_records_for(surface.material_category)
        else:
            records = _fetch_and_parse(surface.material_category, DOWNLOADS_DIR)

        if not records:
            print(f"   No EPD records found for '{surface.material_category}' - skipping.\n")
            continue

        print(f"   Found {len(records)} EPD records.")

        # Step 4: carbon calculation
        carbon_results = calculate_all(records, surface)
        print(f"   Calculated carbon for {len(carbon_results)} materials.")

        # Step 5: ranking
        ranked = rank_materials(carbon_results, site_location=SITE_LOCATION, top_n=5)

        if not ranked:
            print("   No rankable results after carbon calculation - skipping.\n")
            continue

        surface_rankings[surface.surface_id] = ranked
        print(f"   Top pick: {ranked[0].carbon_result.product_name} "
              f"- {ranked[0].carbon_result.total_co2e_kg} kg CO2e\n")

    if not surface_rankings:
        print("No surfaces processed - nothing to report.")
        return

    # Step 6: comparative table
    surface_types = {s.surface_id: s.surface_type.title() for s in SURFACES}
    df = build_comparative_table(surface_rankings, surface_types)
    stats = summary_stats(df)

    csv_path = OUTPUT_DIR / "comparative_table.csv"
    export_table(df, str(csv_path))
    print(f"Comparative table saved -> {csv_path}")

    # Step 7: report
    report_path = OUTPUT_DIR / "carbon_report.pdf"
    generate_report(
        df=df,
        stats=stats,
        output_path=report_path,
        project_name=PROJECT_NAME,
        site_location=SITE_LOCATION,
        building_type=BUILDING_TYPE,
    )
    print(f"Report saved -> {report_path}")

    # Print summary
    print("\n-- Carbon Passport Summary ------------------")
    print(f"  Total CO2e:   {stats['total_co2e_t']} t")
    print(f"  Intensity:    {stats['intensity_kg_m2']} kg/m2")
    print(f"  Benchmark:    {stats['benchmark_kg_m2']} kg/m2")
    print(f"  vs Benchmark: {stats['vs_benchmark_pct']:+.1f}%")
    print("---------------------------------------------")


def _load_sample_records_for(material_category: str):
    """Load sample EPD PDFs that match the material category keyword."""
    from pipeline.pdf_parser import parse_epd_pdf
    keyword = material_category.lower()
    records = []
    for pdf_file in sorted(SAMPLE_PDF_DIR.glob("*.pdf")):
        if keyword in pdf_file.name.lower():
            records.append(parse_epd_pdf(pdf_file))
    # If no name match, return all sample PDFs (useful for initial testing)
    if not records:
        records = [parse_epd_pdf(f) for f in sorted(SAMPLE_PDF_DIR.glob("*.pdf"))]
    return records


def _fetch_and_parse(material_category: str, pdf_dir: Path):
    """Step 1 + 2: fetch from API and parse downloaded PDFs."""
    from pipeline.epd_api import fetch_and_download
    from pipeline.pdf_parser import parse_epd_pdf

    results = fetch_and_download(
        keyword=material_category,
        country="ES",               # Spain for 22@ Barcelona
        output_dir=pdf_dir,
        max_results=10,
    )
    records = []
    for r in results:
        if r["pdf_path"]:
            records.append(parse_epd_pdf(r["pdf_path"]))
        else:
            # API returned data but no PDF — parse from API record directly
            from pipeline.pdf_parser import EPDRecord
            product = r["product"]
            from pipeline.epd_api import extract_gwp_from_api_record
            gwp = extract_gwp_from_api_record(product)
            if gwp:
                rec = EPDRecord(
                    product_name=product.get("name", ""),
                    company=product.get("manufacturer", {}).get("name", "") if isinstance(product.get("manufacturer"), dict) else str(product.get("manufacturer", "")),
                    location=product.get("location", ""),
                    country=product.get("country", ""),
                    declared_unit=product.get("declared_unit", ""),
                    gwp_per_declared_unit=gwp,
                    material_category=material_category,
                )
                records.append(rec)
    return records


if __name__ == "__main__":
    run()
